// <auto-generated />
using System;
using Cember.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cember.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CemberDbContext))]
    [Migration("20260917104748_SyncBrandProfilesModel")]
    partial class SyncBrandProfilesModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cember.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Cember.Domain.Entities.BrandProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("SecondaryColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.ToTable("BrandProfiles");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Circle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowGuestDownloads")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoPublish")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BrandProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverPhotoKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpenJoin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UploadMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BrandProfileId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Circles");
                });

            modelBuilder.Entity("Cember.Domain.Entities.CircleDeletionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VoterGuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VoterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoterGuestSessionId");

                    b.HasIndex("VoterUserId");

                    b.HasIndex("CircleId", "VoterGuestSessionId")
                        .IsUnique()
                        .HasFilter("\"VoterGuestSessionId\" IS NOT NULL");

                    b.HasIndex("CircleId", "VoterUserId")
                        .IsUnique()
                        .HasFilter("\"VoterUserId\" IS NOT NULL");

                    b.ToTable("CircleDeletionVotes", t =>
                        {
                            t.HasCheckConstraint("CK_CircleDeletionVote_ExactlyOneVoter", "(\"VoterUserId\" IS NOT NULL) <> (\"VoterGuestSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cember.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("PhotoId", "CreatedAt");

                    b.ToTable("Comments", t =>
                        {
                            t.HasCheckConstraint("CK_Comment_ExactlyOneAuthor", "(\"UserId\" IS NOT NULL) <> (\"GuestSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cember.Domain.Entities.GoogleLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSub")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("GoogleLinks");
                });

            modelBuilder.Entity("Cember.Domain.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("InviteTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("InviteTokenId");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.ToTable("GuestSessions");
                });

            modelBuilder.Entity("Cember.Domain.Entities.InviteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("InviteTokens");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Preview")
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("RecipientUserId", "CreatedAt");

                    b.HasIndex("RecipientUserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CommercialUseConsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThumbnailKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UploadedByGuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByGuestSessionId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("CircleId", "CreatedAt");

                    b.ToTable("Photos", t =>
                        {
                            t.HasCheckConstraint("CK_Photo_ExactlyOneUploader", "(\"UploadedByUserId\" IS NOT NULL) <> (\"UploadedByGuestSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cember.Domain.Entities.PhotoReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("PhotoId", "GuestSessionId")
                        .IsUnique()
                        .HasFilter("\"GuestSessionId\" IS NOT NULL");

                    b.HasIndex("PhotoId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("PhotoReactions", t =>
                        {
                            t.HasCheckConstraint("CK_PhotoReaction_ExactlyOneAuthor", "(\"UserId\" IS NOT NULL) <> (\"GuestSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cember.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotifyOnComment")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnGuestJoined")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnPhotoAdded")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnReaction")
                        .HasColumnType("boolean");

                    b.Property<bool>("OnlyUploadOnWifi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cember.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Cember.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Circle", b =>
                {
                    b.HasOne("Cember.Domain.Entities.BrandProfile", "BrandProfile")
                        .WithMany("Circles")
                        .HasForeignKey("BrandProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cember.Domain.Entities.User", "Owner")
                        .WithMany("OwnedCircles")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandProfile");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cember.Domain.Entities.CircleDeletionVote", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany("DeletionVotes")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.GuestSession", "VoterGuestSession")
                        .WithMany()
                        .HasForeignKey("VoterGuestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cember.Domain.Entities.User", "VoterUser")
                        .WithMany()
                        .HasForeignKey("VoterUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Circle");

                    b.Navigation("VoterGuestSession");

                    b.Navigation("VoterUser");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Cember.Domain.Entities.GuestSession", "GuestSession")
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cember.Domain.Entities.Photo", "Photo")
                        .WithMany("Comments")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GuestSession");

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cember.Domain.Entities.GoogleLink", b =>
                {
                    b.HasOne("Cember.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cember.Domain.Entities.GuestSession", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany("GuestSessions")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.InviteToken", "InviteToken")
                        .WithMany("GuestSessions")
                        .HasForeignKey("InviteTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("InviteToken");
                });

            modelBuilder.Entity("Cember.Domain.Entities.InviteToken", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany("InviteTokens")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Photo", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany("Photos")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.GuestSession", "UploadedByGuestSession")
                        .WithMany()
                        .HasForeignKey("UploadedByGuestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cember.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Circle");

                    b.Navigation("UploadedByGuestSession");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Cember.Domain.Entities.PhotoReaction", b =>
                {
                    b.HasOne("Cember.Domain.Entities.GuestSession", "GuestSession")
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cember.Domain.Entities.Photo", "Photo")
                        .WithMany("Reactions")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GuestSession");

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cember.Domain.Entities.BrandProfile", b =>
                {
                    b.Navigation("Circles");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Circle", b =>
                {
                    b.Navigation("DeletionVotes");

                    b.Navigation("GuestSessions");

                    b.Navigation("InviteTokens");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Cember.Domain.Entities.InviteToken", b =>
                {
                    b.Navigation("GuestSessions");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Photo", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Cember.Domain.Entities.User", b =>
                {
                    b.Navigation("OwnedCircles");
                });
#pragma warning restore 612, 618
        }
    }
}
