// <auto-generated />
using System;
using Cember.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cember.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CemberDbContext))]
    [Migration("20260907161534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cember.Domain.Entities.Circle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowGuestDownloads")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoPublish")
                        .HasColumnType("boolean");

                    b.Property<string>("CoverPhotoKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Circles");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("PhotoId", "CreatedAt");

                    b.ToTable("Comments", t =>
                        {
                            t.HasCheckConstraint("CK_Comment_ExactlyOneAuthor", "(\"UserId\" IS NOT NULL) <> (\"GuestSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cember.Domain.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("InviteTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("InviteTokenId");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.ToTable("GuestSessions");
                });

            modelBuilder.Entity("Cember.Domain.Entities.InviteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("InviteTokens");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UploadedByGuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByGuestSessionId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("CircleId", "CreatedAt");

                    b.ToTable("Photos", t =>
                        {
                            t.HasCheckConstraint("CK_Photo_ExactlyOneUploader", "(\"UploadedByUserId\" IS NOT NULL) <> (\"UploadedByGuestSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cember.Domain.Entities.PhotoReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("PhotoId", "GuestSessionId")
                        .IsUnique()
                        .HasFilter("\"GuestSessionId\" IS NOT NULL");

                    b.HasIndex("PhotoId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("PhotoReactions", t =>
                        {
                            t.HasCheckConstraint("CK_PhotoReaction_ExactlyOneAuthor", "(\"UserId\" IS NOT NULL) <> (\"GuestSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cember.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("OnlyUploadOnWifi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Circle", b =>
                {
                    b.HasOne("Cember.Domain.Entities.User", "Owner")
                        .WithMany("OwnedCircles")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Cember.Domain.Entities.GuestSession", "GuestSession")
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cember.Domain.Entities.Photo", "Photo")
                        .WithMany("Comments")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GuestSession");

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cember.Domain.Entities.GuestSession", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany("GuestSessions")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.InviteToken", "InviteToken")
                        .WithMany("GuestSessions")
                        .HasForeignKey("InviteTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("InviteToken");
                });

            modelBuilder.Entity("Cember.Domain.Entities.InviteToken", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany("InviteTokens")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Photo", b =>
                {
                    b.HasOne("Cember.Domain.Entities.Circle", "Circle")
                        .WithMany("Photos")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.GuestSession", "UploadedByGuestSession")
                        .WithMany()
                        .HasForeignKey("UploadedByGuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cember.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Circle");

                    b.Navigation("UploadedByGuestSession");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Cember.Domain.Entities.PhotoReaction", b =>
                {
                    b.HasOne("Cember.Domain.Entities.GuestSession", "GuestSession")
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cember.Domain.Entities.Photo", "Photo")
                        .WithMany("Reactions")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cember.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GuestSession");

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Circle", b =>
                {
                    b.Navigation("GuestSessions");

                    b.Navigation("InviteTokens");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Cember.Domain.Entities.InviteToken", b =>
                {
                    b.Navigation("GuestSessions");
                });

            modelBuilder.Entity("Cember.Domain.Entities.Photo", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Cember.Domain.Entities.User", b =>
                {
                    b.Navigation("OwnedCircles");
                });
#pragma warning restore 612, 618
        }
    }
}
